{
 "title": "k8soptimizer Resource Dashboard",
 "tags": [
  "kubernetes",
  "optimization",
  "multi-cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "long_period", "query": "1d, 3d, 7d, 14d, 30d" },
   {
    "name": "cluster",
    "query": "label_values(kube_workload_container_resource_usage_cpu_cores_sum, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_workload_container_resource_usage_cpu_cores_sum{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "workload",
    "query": "label_values(kube_workload_container_resource_usage_cpu_cores_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}, workload)"
   },
   {
    "name": "container",
    "query": "label_values(kube_workload_container_resource_usage_cpu_cores_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\"}, container)"
   },
   {
    "name": "min_memory_investigation_bytes",
    "label": "Minimum Memory requests",
    "query": "0 (All) : 0, 256MiB : 268435456, 512MiB : 536870912, 1024MiB : 1073741824, 2048MiB : 2147483648"
   },
   {
    "name": "min_cpu_requests",
    "label": "Minimum CPU requests",
    "query": "0 (All) : 0, 0.01 : 0.01, 0.10 : 0.10, 0.25 : 0.35, 0.50 : 0.50, 1 : 1"
   }
  ]
 },
 "panels": [
  { "title": "$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Historical CPU & Memory Baseline ($long_period)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(avg_over_time(kube_workload_container_resource_usage_cpu_cores_avg{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"}[$long_period])) by (cluster, namespace, workload, container)"
    },
    {
     "expr": "max(max_over_time(kube_workload_container_resource_usage_cpu_cores_max{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"}[$long_period])) by (cluster, namespace, workload, container)"
    },
    {
     "expr": "max by (cluster, namespace, workload, container) (kube_pod_container_resource_requests{resource=\"cpu\", cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"} * on(cluster, namespace, pod) group_left(workload) max by (cluster, namespace, pod, workload) (namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\"}))"
    },
    {
     "expr": "max by (cluster, namespace, workload, container) (kube_pod_container_resource_limits{resource=\"cpu\", cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"} * on(cluster, namespace, pod) group_left(workload) max by (cluster, namespace, pod, workload) (namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\"}))"
    },
    {
     "expr": "avg(avg_over_time(kube_workload_container_resource_usage_memory_bytes_avg{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"}[$long_period])) by (cluster, namespace, workload, container)"
    },
    {
     "expr": "max(max_over_time(kube_workload_container_resource_usage_memory_bytes_max{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"}[$long_period])) by (cluster, namespace, workload, container)"
    },
    {
     "expr": "max by (cluster, namespace, workload, container) (kube_pod_container_resource_requests{resource=\"memory\", cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"} * on(cluster, namespace, pod) group_left(workload) max by (cluster, namespace, pod, workload) (namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\"}))"
    },
    {
     "expr": "max by (cluster, namespace, workload, container) (kube_pod_container_resource_limits{resource=\"memory\", cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"} * on(cluster, namespace, pod) group_left(workload) max by (cluster, namespace, pod, workload) (namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\"}))"
    },
    {
     "expr": "(\n  max by (cluster, namespace, workload, container) (kube_pod_container_resource_requests{resource=\"cpu\", cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"} * on(cluster, namespace, pod) group_left(workload) max by (cluster, namespace, pod, workload) (namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\"}))\n  /\n  (max(max_over_time(kube_workload_container_resource_usage_cpu_cores_max{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"}[$long_period])) by (cluster, namespace, workload, container) > 0)\n)\nOR on(cluster, namespace, workload, container)\n(\n  max by (cluster, namespace, workload, container) (kube_pod_container_resource_requests{resource=\"cpu\", cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"} * on(cluster, namespace, pod) group_left(workload) max by (cluster, namespace, pod, workload) (namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\"})) * 0\n)"
    },
    {
     "expr": "(\n  max by (cluster, namespace, workload, container) (kube_pod_container_resource_requests{resource=\"memory\", cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"} * on(cluster, namespace, pod) group_left(workload) max by (cluster, namespace, pod, workload) (namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\"}))\n  /\n  (max(max_over_time(kube_workload_container_resource_usage_memory_bytes_max{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"}[$long_period])) by (cluster, namespace, workload, container) > 0)\n)\nOR on(cluster, namespace, workload, container)\n(\n  max by (cluster, namespace, workload, container) (kube_pod_container_resource_requests{resource=\"memory\", cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"} * on(cluster, namespace, pod) group_left(workload) max by (cluster, namespace, pod, workload) (namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\"})) * 0\n)"
    }
   ]
  },
  {
   "title": "CPU Cores Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, workload, container) (kube_workload_container_resource_usage_cpu_cores_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"})",
     "legendFormat": "Sum - {{container}}"
    }
   ]
  },
  {
   "title": "Memory Bytes Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, workload, container) (kube_workload_container_resource_usage_memory_bytes_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"})",
     "legendFormat": "Sum - {{container}}"
    }
   ]
  },
  {
   "title": "CPU 1-Week Prediction vs Actual",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (cluster, namespace, container) (kube_workload_container_resource_usage_cpu_cores_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"})",
     "legendFormat": "Actual CPU Sum - {{container}}"
    },
    {
     "expr": "max by (cluster, namespace, container) (kube_workload_container_resource_usage_cpu_cores_sum:avg_over_time_1w{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"})",
     "legendFormat": "1W Average Baseline - {{container}}"
    }
   ]
  },
  {
   "title": "OOM Killed Events",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_workload_container_resource_usage_memory_oom_killed{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", container=~\"$container\"}",
     "legendFormat": "{{cluster}} / {{container}}"
    }
   ]
  }
 ]
}