{
 "title": "k8soptimizer GitLab Runner Dashboard",
 "tags": [
  "gitlab-runner",
  "k8soptimizer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "long_period", "query": "1d, 3d, 7d, 14d, 30d" },
   {
    "name": "cluster",
    "query": "label_values(gitlab_job_container_resource_usage_cpu_cores_max, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(gitlab_job_container_resource_usage_cpu_cores_max{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "project",
    "query": "label_values(gitlab_job_container_resource_usage_cpu_cores_max{cluster=~\"$cluster\", namespace=~\"$namespace\"}, label_gitlab_project)"
   },
   {
    "name": "job_name",
    "query": "label_values(gitlab_job_container_resource_usage_cpu_cores_max{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\"}, label_gitlab_job_name)"
   },
   {
    "name": "container",
    "query": "label_values(gitlab_job_container_resource_usage_cpu_cores_max{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\"}, container)"
   },
   {
    "name": "min_memory_investigation_bytes",
    "label": "Minimum Memory requests",
    "query": "0 (All) : 0, 256MiB : 268435456, 512MiB : 536870912, 1024MiB : 1073741824, 2048MiB : 2147483648"
   },
   {
    "name": "min_cpu_requests",
    "label": "Minimum CPU requests",
    "query": "0 (All) : 0, 0.01 : 0.01, 0.10 : 0.10, 0.25 : 0.35, 0.50 : 0.50, 0.100 : 0.100, 0.250 : 0.250, 0.500 : 0.500, 1 : 1"
   }
  ]
 },
 "panels": [
  { "title": "$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Historical CPU & Memory Baseline ($long_period) - GitLab Runners",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_job_container_resource_usage_cpu_cores_avg{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\", container!=\"\"}[$long_period])) by (namespace, label_gitlab_project, label_gitlab_job_name, container)"
    },
    {
     "expr": "max(max_over_time(gitlab_job_container_resource_usage_cpu_cores_max{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\", container!=\"\"}[$long_period])) by (namespace, label_gitlab_project, label_gitlab_job_name, container)"
    },
    {
     "expr": "max by (namespace, label_gitlab_project, label_gitlab_job_name, container) (\n  gitlab_job_container_resource_requests{resource=\"cpu\", cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"}\n)"
    },
    {
     "expr": "max by (namespace, label_gitlab_project, label_gitlab_job_name, container) (\n  gitlab_job_container_resource_limits{resource=\"cpu\", cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"}\n)"
    },
    {
     "expr": "avg(avg_over_time(gitlab_job_container_resource_usage_memory_bytes_avg{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\", container!=\"\"}[$long_period])) by (namespace, label_gitlab_project, label_gitlab_job_name, container)"
    },
    {
     "expr": "max(max_over_time(gitlab_job_container_resource_usage_memory_bytes_max{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\", container!=\"\"}[$long_period])) by (namespace, label_gitlab_project, label_gitlab_job_name, container)"
    },
    {
     "expr": "max by (namespace, label_gitlab_project, label_gitlab_job_name, container) (\n  gitlab_job_container_resource_requests{resource=\"memory\", cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"}\n)"
    },
    {
     "expr": "max by (namespace, label_gitlab_project, label_gitlab_job_name, container) (\n  gitlab_job_container_resource_limits{resource=\"memory\", cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"}\n)"
    },
    {
     "expr": "(\n  max by (namespace, label_gitlab_project, label_gitlab_job_name, container) (\n    max_over_time(gitlab_job_container_resource_requests{resource=\"cpu\", cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"}[$long_period])\n  )\n  /\n  (max(max_over_time(gitlab_job_container_resource_usage_cpu_cores_max{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\", container!=\"\"}[$long_period])) by (namespace, label_gitlab_project, label_gitlab_job_name, container) > 0)\n)"
    },
    {
     "expr": "(\n  max by (namespace, label_gitlab_project, label_gitlab_job_name, container) (\n    max_over_time(gitlab_job_container_resource_requests{resource=\"memory\", cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"}[$long_period])\n  )\n  /\n  (max(max_over_time(gitlab_job_container_resource_usage_memory_bytes_max{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\", container!=\"\"}[$long_period])) by (namespace, label_gitlab_project, label_gitlab_job_name, container) > 0)\n)"
    }
   ]
  },
  {
   "title": "Usage Graphs for $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 238 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores Usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 700 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (cluster, namespace, label_gitlab_project, label_gitlab_job_name, container) (gitlab_job_container_resource_usage_cpu_cores_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"})",
       "legendFormat": "Sum - {{container}}"
      }
     ]
    },
    {
     "title": "Memory Bytes Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 711 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (cluster, namespace, label_gitlab_project, label_gitlab_job_name, container) (gitlab_job_container_resource_usage_memory_bytes_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"})",
       "legendFormat": "Sum - {{container}}"
      }
     ]
    },
    {
     "title": "CPU 1-Week Prediction vs Actual",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 721 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (cluster, namespace, container) (gitlab_job_container_resource_usage_cpu_cores_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"})",
       "legendFormat": "Actual CPU Sum - {{container}}"
      },
      {
       "expr": "max by (cluster, namespace, container) (gitlab_job_container_resource_usage_cpu_cores_sum:avg_over_time_1w{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"})",
       "legendFormat": "1W Average Baseline - {{container}}"
      }
     ]
    },
    {
     "title": "OOM Killed Events",
     "type": "stat",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 731 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gitlab_job_container_resource_usage_memory_oom_killed{cluster=~\"$cluster\", namespace=~\"$namespace\", label_gitlab_project=~\"$project\", label_gitlab_job_name=~\"$job_name\", container=~\"$container\"}",
       "legendFormat": "{{cluster}} / {{container}}"
      }
     ]
    }
   ]
  }
 ]
}